Add PR and issue templates
physiopy/peakdet pull request #40
Opened 2021-01-25 12:11 UTC by smoia

This should appear as a co-authorship. If it doesn't, I'm going to check why.

2021-01-25 15:46 UTC, tsalo commented
WDYT about adding a NeuroStars link for usage questions, like we did for `tedana`?

2021-01-25 15:49 UTC, smoia commented
Can you explain a bit more - like, in what does it consists?
(Also, I'm not sure I want to spread the channels of communication more than we do now. That's a question for the community, but we can ask it at the dev call in February)

2021-01-25 16:25 UTC, tsalo commented
The idea is just to point usage questions toward NeuroStars instead of issues. As the issue template selection page, there's a link to the NeuroStars `tedana`-tagged topics page, so that users can see what questions have already been asked and, if they do open a new topic, the `tedana` tag is automatically added. See below for how it looks:

<img width="1438" alt="Screen Shot 2021-01-25 at 11 14 43 AM" src="https://user-images.githubusercontent.com/8228902/105732822-dbf67b80-5efe-11eb-9e07-c12f6f66bb76.png">

One benefit to having usage questions on NeuroStars is that ones which relate to multiple `physiopy` repositories will be easier to track since they won't be linked to a specific repo.

2021-01-25 16:27 UTC, smoia commented
Fair enough! @physiopy/all what do you think?
Would there be someone monitoring the whole time Neurostars though? (I guess we can set up alerts, but the question is: once people ask, is there someone that will answer?)

2021-03-11 22:44 UTC, smoia commented
@tsalo I *think* I added the link to neurostars, but if you could have a look at it, you'd do a big favor!

2021-03-11 23:02 UTC, tsalo requested changes
I just noticed one minor typo. The NeuroStars link looks good!

2021-03-11 23:02 UTC, tsalo commented on .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE_FEATURE_REQUEST.md
> +labels: Enhacement
```suggestion
labels: Enhancement
```

2021-03-12 15:26 UTC, tsalo approved these changes
LGTM!

2021-03-12 16:27 UTC, merged